### ISSUE TITLE
msgpack-python is deprecated, use msgpack

### ISSUE THREAD

**Issue by brianmaissy** [choleraehyq/aiorpc#20]
> This package is deprecated. Install msgpack instead.

https://pypi.org/project/msgpack-python/

When users install both msgpack and aiorpc they will have both msgpack and msgpack-python installed, which conflict.

**Comment by volfco** [comment]
Good catch. I'll fix this weekend and publish an updated version with the other fixes

**Comment by volfco** [comment]
I just pushed v0.1.5 which uses the msgpack package. You shouldn't see those warnings.

**Comment by brianmaissy** [comment]
Thanks!

**Comment by volfco** [comment]
I just need @choleraehyq to publish the new build

**Comment by choleraehyq** [comment]
@volfco Done.

**Comment by brianmaissy** [comment]
The issue is not resolved, you still have `msgpack-python` listed under `install_requires` in your `setup.py`

**Comment by volfco** [comment]
@brianmaissy Sorry about that. My mistake. 

@choleraehyq Can you push v0.1.6? Sorry lol

**Comment by choleraehyq** [comment]
@volfco Done :)

**Comment by orpinchasov** [comment]
I still don't manage to get this working with aiorpc 0.1.6 and msgpack 1.0.0.

In line 140 of client.py you're passing the argument 'encoding' to msgpack.packb, which passes it on to the constructor of Packer (msgpack.__init__:788), which doesn't accept this argument any more.

This is the original error:
```
Traceback (most recent call last):
  File "env/lib/python3.6/site-packages/aiorpc/client.py", line 86, in call
    req = self._create_request(method, args)
  File "env/lib/python3.6/site-packages/aiorpc/client.py", line 140, in _create_request
    return msgpack.packb(req, encoding=self._pack_encoding, **self._pack_params)
  File "env/lib/python3.6/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 118, in msgpack._cmsgpack.Packer.__init__
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

Can you check this out? Thanks

**Comment by orpinchasov** [comment]
Actually, I found a couple more of these in client.py and server.py (if you look for "encoding=" you'll find it). I removed them trying to make my code work and it does, but you can give a smarter solution for sure.

**Comment by volfco** [comment]
Sure. Test cases ran fine under Python 3.8, but either this is a lack of coverage or something that happens under Python 3.6. 

I'll update when I figure it out

**Comment by thekafkaf** [comment]
Have the same issue with 
aiorpc==0.1.6 
msgpack==1.0.0
python==3.6

Thanks for the hard work :)
